# Generated by Django 5.1.3 on 2024-12-19 11:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(blank=True, help_text='Dirección de correo electrónico única para cada usuario. Puede dejarse en blanco si se utiliza otro identificador.', max_length=254, null=True, unique=True)),
                ('username', models.CharField(blank=True, help_text='Nombre de usuario único. Puede contener letras y números, sin espacios.', max_length=30, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, help_text='Número de celular único del usuario, solo se permiten dígitos.', max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'El número de celular solo debe contener dígitos.')])),
                ('name', models.CharField(blank=True, help_text='Nombre del usuario.', max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, help_text='Apellido del usuario.', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la cuenta está activa.')),
                ('is_staff', models.BooleanField(default=False, help_text='Indica si el usuario tiene acceso al panel de administración.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indica si el usuario fue eliminado de forma lógica.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en la que se creó el usuario.')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
