# Generated by Django 5.1.3 on 2024-12-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Indica si el usuario fue eliminado de forma lógica.'),
        ),
    ]
