# Generated by Django 5.1.3 on 2024-12-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spanish_name', models.CharField(help_text="Nombre del país en español (Ej: 'Afganistán').", max_length=100)),
                ('english_name', models.CharField(help_text="Nombre del país en inglés (Ej: 'Afghanistan').", max_length=100)),
                ('alpha_3', models.CharField(help_text="Código Alpha-3 del país según ISO 3166 (Ej: 'AFG').", max_length=3, unique=True)),
                ('alpha_2', models.CharField(help_text="Código Alpha-2 del país según ISO 3166 (Ej: 'AF').", max_length=2, unique=True)),
                ('numeric_code', models.PositiveIntegerField(help_text="Código numérico del país según ISO 3166 (Ej: '4').", unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(help_text="Código único del departamento (Ej: '05' para Antioquia).", unique=True)),
                ('name', models.CharField(help_text="Nombre del departamento (Ej: 'Antioquia').", max_length=100)),
                ('country_numeric_code', models.PositiveIntegerField(help_text="Código numérico del país al que pertenece este departamento, enlazado por 'numeric_code' de Country.")),
            ],
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(help_text="Código único del municipio (Ej: '5001' para Medellín).", unique=True)),
                ('name', models.CharField(help_text="Nombre del municipio (Ej: 'Medellín').", max_length=100)),
                ('department_code', models.PositiveIntegerField(help_text="Código del departamento al que pertenece este municipio, enlazado por 'code' de Department.")),
            ],
        ),
    ]
