# Generated by Django 5.1.3 on 2025-02-13 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_diversa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='subquestion',
            field=models.ForeignKey(blank=True, help_text='Subpregunta a la que pertenece esta opción. Dejar en blanco si pertenece a una pregunta.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option_set', to='app_diversa.subquestion'),
        ),
    ]
