# Generated by Django 5.1.3 on 2024-12-19 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_diversa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='user',
            field=models.ForeignKey(help_text='Usuario que proporcionó esta respuesta.', on_delete=django.db.models.deletion.CASCADE, related_name='responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subquestion',
            name='parent_question',
            field=models.ForeignKey(help_text='Pregunta principal a la que pertenece esta subpregunta.', on_delete=django.db.models.deletion.CASCADE, related_name='subquestions', to='app_diversa.question'),
        ),
        migrations.AddField(
            model_name='option',
            name='subquestion',
            field=models.ForeignKey(blank=True, help_text='Subpregunta a la que pertenece esta opción. Dejar en blanco si pertenece a una pregunta.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='app_diversa.subquestion'),
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(help_text='Encuesta a la que pertenece esta pregunta.', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app_diversa.survey'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='survey',
            field=models.ForeignKey(help_text='Encuesta a la que pertenece este capítulo.', on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='app_diversa.survey'),
        ),
        migrations.AddField(
            model_name='surveytext',
            name='survey',
            field=models.ForeignKey(help_text='Survey to which this text belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='app_diversa.survey'),
        ),
    ]
