# Generated by Django 5.1.3 on 2024-11-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_diversa', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='option_type',
            field=models.CharField(blank=True, choices=[('COUNTRY', 'País'), ('DEPARTMENT', 'Departamento'), ('MUNICIPALITY', 'Municipio')], help_text='Especifica el tipo de esta opción.', max_length=20, null=True),
        ),
    ]
