# Generated by Django 5.1.3 on 2024-12-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_diversa', '0003_option_option_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora en que se actualizó el capítulo.'),
        ),
        migrations.AddField(
            model_name='option',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora en que se actualizó la opción.'),
        ),
        migrations.AddField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora en que se actualizó la pregunta.'),
        ),
        migrations.AddField(
            model_name='response',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora en que se actualizó la respuesta.'),
        ),
        migrations.AddField(
            model_name='survey',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora en que se actualizó la encuesta.'),
        ),
        migrations.AddField(
            model_name='surveytext',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora en que se actualizó el texto.'),
        ),
    ]
