# Generated by Django 5.1.3 on 2025-02-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_diversa', '0003_alter_option_subquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subquestion',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
