# Generated by Django 5.1.3 on 2024-12-28 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_diversa', '0004_subquestion_custom_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='matrix_layout_type',
            field=models.CharField(blank=True, choices=[('row', 'Matriz - Fila'), ('column', 'Matriz - Columna')], help_text="Diseño para preguntas tipo matriz: 'Fila' (row) u 'Columna' (column).", max_length=10, null=True),
        ),
    ]
