# Generated by Django 5.1.3 on 2025-02-18 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_diversa', '0004_alter_subquestion_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='country_code',
            field=models.IntegerField(blank=True, help_text='Código numérico del país seleccionado.', null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='department_code',
            field=models.IntegerField(blank=True, help_text='Código del departamento seleccionado.', null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='municipality_code',
            field=models.IntegerField(blank=True, help_text='Código del municipio seleccionado.', null=True),
        ),
    ]
