# Generated by Django 5.1.3 on 2024-12-06 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_diversa', '0005_question_is_multiple'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Orden de la pregunta dentro de la encuesta.'),
        ),
    ]
