# Generated by Django 5.1.3 on 2025-02-26 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_diversa', '0005_response_country_code_response_department_code_and_more'),
        ('app_geo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='response',
            name='department_code',
        ),
        migrations.RemoveField(
            model_name='response',
            name='municipality_code',
        ),
        migrations.AddField(
            model_name='response',
            name='new_department',
            field=models.ForeignKey(blank=True, help_text='Nuevo departamento seleccionado (pregunta 7).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses_new_departments', to='app_geo.department'),
        ),
        migrations.AddField(
            model_name='response',
            name='new_municipality',
            field=models.ForeignKey(blank=True, help_text='Nuevo municipio seleccionado (pregunta 7).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses_new_municipalities', to='app_geo.municipality'),
        ),
    ]
