# Generated by Django 5.1.3 on 2024-12-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_diversa', '0006_question_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='description',
        ),
        migrations.AddField(
            model_name='survey',
            name='description_name',
            field=models.TextField(blank=True, help_text='Descripción detallada de la encuesta, se muestra debajo del name en el encabezado de la encuesta. Opcional.', null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='description_title',
            field=models.TextField(blank=True, help_text='Descripción del título de la encuesta que se muestra en las cards del índice.', null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='title',
            field=models.CharField(default='TÍTULO POR DEFECTO', help_text='Título de la encuesta que se muestra en las cards del índice. Obligatorio.', max_length=255),
        ),
        migrations.AlterField(
            model_name='survey',
            name='name',
            field=models.CharField(help_text='Nombre de la encuesta, se muestra en el encabezado de la encuesta. Máximo 255 caracteres.', max_length=255),
        ),
    ]
