# Generated by Django 5.1.3 on 2025-03-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_diversa', '0006_remove_response_country_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='other_text',
            field=models.TextField(blank=True, help_text="Texto ingresado por el usuario cuando selecciona la opción 'Otro'.", null=True),
        ),
    ]
