# Generated by Django 5.1.3 on 2025-03-10 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_diversa', '0007_response_other_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='note',
            field=models.TextField(blank=True, help_text='Nota aclaratoria para la pregunta. Opcional.', null=True),
        ),
        migrations.AddField(
            model_name='subquestion',
            name='note',
            field=models.TextField(blank=True, help_text='Nota aclaratoria para la subpregunta. Opcional.', null=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='note',
            field=models.TextField(blank=True, help_text='Nota aclaratoria para la opción. Opcional.', null=True),
        ),
    ]
