# Generated by Django 5.1.3 on 2024-12-10 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_diversa', '0007_remove_survey_description_survey_description_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='text',
            new_name='text_option',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='order',
            new_name='order_question',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='text_question',
        ),
        migrations.AddField(
            model_name='option',
            name='order_option',
            field=models.PositiveIntegerField(default=0, help_text='Orden de la opción.'),
        ),
        migrations.AddField(
            model_name='option',
            name='order_question',
            field=models.PositiveIntegerField(blank=True, help_text='Orden de la pregunta a la que pertenece esta opción.', null=True),
        ),
    ]
