# Generated by Django 5.1.3 on 2024-12-11 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_diversa', '0009_question_is_subquestion_question_parent_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='data_type',
        ),
        migrations.RemoveField(
            model_name='question',
            name='geography_type',
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_geographic',
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_multiple',
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_subquestion',
        ),
        migrations.RemoveField(
            model_name='question',
            name='max_value',
        ),
        migrations.RemoveField(
            model_name='question',
            name='min_value',
        ),
        migrations.RemoveField(
            model_name='question',
            name='parent_order',
        ),
    ]
