# Generated by Django 5.1.3 on 2025-03-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_diversa', '0009_alter_response_new_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyattempt',
            name='birth_day',
        ),
        migrations.RemoveField(
            model_name='surveyattempt',
            name='birth_month',
        ),
        migrations.RemoveField(
            model_name='surveyattempt',
            name='birth_year',
        ),
        migrations.AddField(
            model_name='surveyattempt',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Fecha de nacimiento del participante en formato YYYY-MM-DD.', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('open', 'Pregunta Abierta'), ('closed', 'Pregunta Cerrada'), ('likert', 'Escala Likert'), ('rating', 'Escala de Puntuación'), ('matrix', 'Pregunta Matricial'), ('birth_date', 'Fecha de Nacimiento')], help_text="Tipo de la pregunta, por ejemplo: 'open', 'closed', etc.", max_length=10),
        ),
    ]
