# Generated by Django 5.1.3 on 2025-03-20 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_diversa', '0010_remove_surveyattempt_birth_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subquestion',
            name='is_other',
            field=models.BooleanField(default=False, help_text="Indica si esta opción representa la respuesta 'Otro'."),
        ),
    ]
