# Generated by Django 5.1.3 on 2024-12-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_diversa', '0010_remove_question_data_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='order_question',
        ),
        migrations.AddField(
            model_name='question',
            name='data_type',
            field=models.CharField(blank=True, help_text="Tipo de dato esperado, por ejemplo: 'integer', 'string', etc. Opcional.", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='geography_type',
            field=models.CharField(blank=True, choices=[('COUNTRY', 'País'), ('DEPARTMENT', 'Departamento'), ('MUNICIPALITY', 'Municipio')], help_text='Especifica el nivel geográfico (país, departamento o municipio).', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='is_geographic',
            field=models.BooleanField(default=False, help_text='Indica si la pregunta requiere selección geográfica.'),
        ),
        migrations.AddField(
            model_name='question',
            name='is_multiple',
            field=models.BooleanField(default=False, help_text='Indica si la pregunta permite seleccionar múltiples opciones.'),
        ),
        migrations.AddField(
            model_name='question',
            name='max_value',
            field=models.IntegerField(blank=True, help_text='Valor máximo permitido para respuestas numéricas. Opcional.', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='min_value',
            field=models.IntegerField(blank=True, help_text='Valor mínimo permitido para respuestas numéricas. Opcional.', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='subquestion_order',
            field=models.PositiveIntegerField(blank=True, help_text='Orden de la subpregunta dentro de una matriz.', null=True),
        ),
    ]
