# Generated by Django 5.1.3 on 2025-03-20 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_diversa', '0011_subquestion_is_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='subquestion',
            field=models.ForeignKey(blank=True, help_text='Subpregunta a la que corresponde esta respuesta. Puede ser nulo si la respuesta es para una pregunta principal.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='app_diversa.subquestion'),
        ),
    ]
