# Generated by Django 5.1.3 on 2025-03-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_diversa', '0012_response_subquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='new_department',
            field=models.IntegerField(blank=True, help_text='ID del nuevo departamento seleccionado (pregunta 8).', null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='new_municipality',
            field=models.IntegerField(blank=True, help_text='ID del nuevo municipio seleccionado (pregunta 8).', null=True),
        ),
    ]
