# Generated by Django 5.1.3 on 2025-03-20 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_diversa', '0013_alter_response_new_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='option_selected',
            field=models.ForeignKey(blank=True, help_text='Opción seleccionada para preguntas cerradas. Opcional.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='response_option_selected', to='app_diversa.option'),
        ),
        migrations.RemoveField(
            model_name='response',
            name='options_multiple_selected',
        ),
        migrations.AddField(
            model_name='response',
            name='options_multiple_selected',
            field=models.ManyToManyField(blank=True, help_text='Opciones seleccionadas para preguntas de selección múltiple.', related_name='response_options_multiple_selected', to='app_diversa.option'),
        ),
    ]
