# Generated by Django 5.1.3 on 2025-03-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_diversa', '0014_alter_response_option_selected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('open', 'Pregunta Abierta'), ('closed', 'Pregunta Cerrada'), ('likert', 'Escala Likert'), ('rating', 'Escala de Puntuación'), ('matrix', 'Pregunta Matricial'), ('birth_date', 'Fecha de Nacimiento'), ('multiple', 'Respuesta múltiple')], help_text="Tipo de la pregunta, por ejemplo: 'open', 'closed', etc.", max_length=10),
        ),
    ]
