# Generated by Django 5.1.3 on 2025-03-22 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_diversa', '0015_alter_question_question_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Identificador del mensaje (ej: success_message, rejection_msg_1)', max_length=100, unique=True)),
                ('title', models.CharField(help_text='Título del mensaje', max_length=255)),
                ('content', models.TextField(help_text='Contenido HTML del mensaje')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
