# Generated by Django 5.1.3 on 2025-03-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_diversa', '0017_remove_response_new_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyattempt',
            name='success_note',
            field=models.TextField(blank=True, help_text='Mensaje de éxito si se enviaron satisfactoriamente todas las respuestas de la encuesta.', null=True),
        ),
    ]
