# Generated by Django 5.1.3 on 2025-03-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_diversa', '0018_surveyattempt_success_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='normalized_other_text',
            field=models.TextField(blank=True, editable=False, help_text="Texto 'otro' en minúsculas y sin tildes para análisis.", null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='normalized_response_text',
            field=models.TextField(blank=True, editable=False, help_text='Texto de respuesta (response_text) normalizado en minúsculas y sin tildes.', null=True),
        ),
    ]
